name: Deploy Flask to EC2 with Docker

on:
  push:
    branches:
      - CI/CD-Test 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<EOF
          cd flask-backend
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
          EOF


      - name: Download Model from S3
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          aws s3 cp s3://agriconnect2025/plant_disease_model.h5 /home/ubuntu/flask-backend/plant_disease_model.h5
          EOF
